apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: java-intergrated-wordcount
spec:
  image: first-flink-demo:1.15.3.2023100109
  flinkVersion: v1_15
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
  serviceAccount: default
  jobManager:
    resource:
      memory: "1024m"
      cpu: 1
  taskManager:
    resource:
      memory: "1024m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/apps/first-flink-demo.jar
    parallelism: 2
    upgradeMode: stateless